services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cicd
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: cicd
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: mimosay/cicd-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cicd
      SPRING_DATASOURCE_USERNAME: cicd
      SPRING_DATASOURCE_PASSWORD: cicd
    depends_on:
      - db
    ports:
      - "80:8080"
    restart: unless-stopped

volumes:
  db_data:
